version: '3'

services:
  app:
    build:
      context: ./                   # Path to the directory containing Dockerfile for app
      dockerfile: Dockerfile.app                # Name of the Dockerfile for app
    ports:
      - "8083:8083" # Port for the API/app
    environment:
      - SPRING_PROFILES_ACTIVE=app
      # - TEMPORAL_SERVER=temporal:7233
    network_mode: host



  publish-banner-worker:
    build:
      context: ./ # Path to the directory containing Dockerfile for publish-banner-worker
      dockerfile: Dockerfile.PublishBannerMessageWorker     # Name of the Dockerfile for publish-banner-worker
    ports:
      - "8081:8081" # Port for publish-banner-worker
    environment:
      - SPRING_PROFILES_ACTIVE=publish-banner-worker
      # - TEMPORAL_SERVER='temporal:7233'
    network_mode: host

  schedule-payment-worker:
    build:
      context: ./ # Path to the directory containing Dockerfile for schedule-payment-worker
      dockerfile: Dockerfile.SchedulePaymentWorker   # Name of the Dockerfile for schedule-payment-worker
    ports:
      - "8082:8082" # Port for schedule-payment-worker
    environment:
      - SPRING_PROFILES_ACTIVE=payment-schedule-worker
      # - TEMPORAL_SERVER='temporal:7233'
    network_mode: host