spring:
  profiles:
    active: "app"

server:
  port: 8081

temporal:
  task-queue: "ScheduledPaymentQueue"

  # App-specific temporal configuration
  workflows:
    payment:
      version: v1
      execution-timeout: 30m
      run-timeout: 15m

logging:
  level:
    root: INFO
    com.github.sardul3.temporal_boot.app: DEBUG
