---
spring:
  config:
    activate:
      on-profile: worker

temporal:
  task-queue: "ScheduledPaymentQueue"

  activities:
    createScheduledTask:
      schedule-to-close-timeout: 5m
      start-to-close-timeout: 2m
      retry:
        initial-interval: 10s
        max-attempts: 3
        backoff-coefficient: 2.0

    runSchedulePayment:
      schedule-to-close-timeout: 10m
      start-to-close-timeout: 5m
      retry:
        initial-interval: 15s
        max-attempts: 5
        backoff-coefficient: 1.5
temporal:
  server: localhost:8080
  namespace: default

logging:
  level:
    root: INFO
    com.github.sardul3.temporal_boot.worker: DEBUG
