spring:
  config:
    activate:
      on-profile: "app"

server:
  port: 8080

temporal:
  task-queue: "ScheduledPaymentQueue"

logging:
  level:
    root: INFO
    com.github.sardul3.temporal_boot.app: DEBUG
